### ISSUE TITLE
ambiguous indirect export: ChartPieSolid

### ISSUE THREAD

**Issue by MindSetFPS** [themesberg/flowbite-svelte-icons#24]
It was working in the previous version I was using (1.0.2).
Node: 20.10.0

"flowbite": "^2.2.1",
"flowbite-svelte": "^0.44.22",
"flowbite-svelte-icons": "^1.0.2",
"svelte": "^4.2.7",
"tslib": "^2.4.1",
"typescript": "^5.0.
"vite": "^5.0.3"

RollupError: "ChartPieSolid" is not exported by "node_modules/flowbite-svelte-icons/dist/index.js", imported by "src/components/sideBar.svelte".
    at error (file:///home/daniel/Documents/projects/wa-assitant/frontend/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at Module.error (file:///home/daniel/Documents/projects/wa-assitant/frontend/node_modules/rollup/dist/es/shared/node-entry.js:12781:16)
    at Module.traceVariable (file:///home/daniel/Documents/projects/wa-assitant/frontend/node_modules/rollup/dist/es/shared/node-entry.js:13218:29)
    at ModuleScope.findVariable (file:///home/daniel/Documents/projects/wa-assitant/frontend/node_modules/rollup/dist/es/shared/node-entry.js:11635:39)
    at ReturnValueScope.findVariable (file:///home/daniel/Documents/projects/wa-assitant/frontend/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
    at FunctionBodyScope.findVariable (file:///home/daniel/Documents/projects/wa-assitant/frontend/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
    at ReturnValueScope.findVariable (file:///home/daniel/Documents/projects/wa-assitant/frontend/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
    at FunctionBodyScope.findVariable (file:///home/daniel/Documents/projects/wa-assitant/frontend/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
    at ReturnValueScope.findVariable (file:///home/daniel/Documents/projects/wa-assitant/frontend/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
    at FunctionBodyScope.findVariable (file:///home/daniel/Documents/projects/wa-assitant/frontend/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)

**Comment by shinokada** [comment]
Can you use the latest and search your icon at https://flowbite-svelte-icons.vercel.app/solid.
Please be noted that there are many icon names are changed.
